What good weather!
VolffS/weather pull request #1
Opened 2024-03-14 14:18 UTC by VolffS

2024-03-14 15:36 UTC, xDSUP commented on src/components/week-info/week-info.tsx
> +export const WeekInfo = ({weatherInfo, onDayClick, currentMetric}: {
onDayClick название неудачное для такого обьекта, передавай уж по отдельности

2024-03-14 15:48 UTC, xDSUP commented on src/components/week-info/week-info.tsx
> +                            onDayClick.selectWeatherDay(+ev.currentTarget.id);
не используй id, а кидай сразу индекс)

2024-03-14 15:49 UTC, xDSUP commented on src/components/week-info/week-info.tsx
> +    const dataWeek: Array<WeeksWeatherData> = formattingWeeksWeatherData(weatherInfo);
непонятно, откуда берется 4 элемента - тупа магия)

2024-03-14 15:52 UTC, xDSUP commented on src/components/main-content/main-content.tsx
> +                    <CurrentWeather weather={stateWeather} weatherDay={weatherDay} currentMetric={weatherMetric}/>
давай попробуем передавать просто текущий элемент, а не массив и индекс

2024-03-14 15:53 UTC, xDSUP commented on src/components/main-content/main-content.tsx
> +                    weather.main.temp = weather.main.temp * 1.8 + 32
давай расчитывать это там, где мы показываем температуру, а не менять значения в массиве

2024-03-14 15:57 UTC, xDSUP commented on src/components/main-content/main-content.tsx
> +        if (weatherDay === day) {
weatherDay - переименовый в activeDay или чет подобное

2024-03-14 15:58 UTC, xDSUP commented on src/components/main-content/main-content.tsx
> +    const [weatherMetric, setWeatherMetric] = useState<Metric>(Metric.celsius);
перепеши с использованием useContext, попробуем что-то новое)

2024-03-14 16:00 UTC, xDSUP commented on src/components/main-content/main-content.tsx
> +        navigator.geolocation.getCurrentPosition(successGetCurrentPosition);
Крутая штука, даже не закрашилось, если ничего не выбрать) (лайк)

2024-03-14 16:02 UTC, xDSUP commented on src/components/main-content/main-content.tsx
> +    const [stateWeather, setStateWeather] = useState<WeatherData>({
хочется все-таки лоадера, если данные грузятся, а не просто нулей) 

давай при загрузке докинем лоадер, а если город не найден, или польз не дал геолокацию выводить только changeLocation

2024-03-14 16:03 UTC, xDSUP commented on src/components/main-content/main-content.tsx
> +                        const date = new Date(day.dt_txt).getHours();
лучше спрятать в какую-то функцию, или даже внутрь requestWeatherFiveDays.

или промежуточный файлик какой-то завести, где будет логика преобразования данных, получ от сервера.

2024-03-14 16:07 UTC, xDSUP commented on src/components/main-content/main-content.tsx
> +    const downEscapeHandler = (ev: KeyboardEvent): void => {
круто, и кажется это дожно быть где-то на уровне CountrySearch

2024-03-14 16:10 UTC, xDSUP commented on src/components/main-content/main-content.tsx
> +        window.addEventListener("keydown", downEscapeHandler)
такие глобальные события использовать слишком опасно, и кстати, на будущее, listener нужно снимать при unmount компонента. погугли, как это сделать. 

тут бы немного иначе сделать. В виде модального окна, с затемнением фона сзади + заблокировать все сзади, нужно погуглить, как это делается, а на это затемнение как раз все листененры и навесить.

2024-03-14 16:12 UTC, xDSUP commented on src/components/search-result-list/search-result-list.tsx
> +export const SearchResultList = ({cities, onDivClick}: {
onDivClick - почему-то не функция) onDivClick по названию должен идти в событие onclick элемента див

2024-03-14 16:12 UTC, xDSUP commented on src/components/search-result-list/search-result-list.tsx
> +        <ul className="country-search__result">
за форматирование и двор... Поправьте, пожалуйста, читать очень тяжело

2024-03-14 16:15 UTC, xDSUP commented on src/components/side-information/side-information.tsx
> +export const SideInformation = ({weather, onBtnClick, useWeatherDay, currentMetric}: {
onBtnClick - название более точное нужно, а то на какую кнопку то это клик?)

2024-03-14 16:38 UTC, xDSUP commented on src/components/side-information/side-information.tsx
> +        <WeekInfo weatherInfo={weather} onDayClick={useWeatherDay} currentMetric={currentMetric}/>
а массив бы мб и тут обрезать до 4)

2024-03-14 16:39 UTC, xDSUP commented on src/components/current-weather/current-weather.tsx
> +    const weatherData: TodayWeather = formattingWeatherByDate(weather, weatherDay, currentMetric);
я бы пустышки для данных мб убрал, тк должен быть лоадер, или сообщение о том, что погоды нет)

2024-03-14 16:48 UTC, xDSUP commented on src/type/geolocation.ts
> +        accuracy: number,
лишнее удалить, тип сюда подставить)

2024-03-14 16:49 UTC, xDSUP requested changes
Поправьте комменты)

2024-03-14 16:50 UTC, xDSUP commented on src/helpers/helpers.ts
> +export function throttle(func, ms) {
типочки нужны

2024-03-15 02:37 UTC, VolffS commented on src/components/week-info/week-info.tsx
> +export const WeekInfo = ({weatherInfo, onDayClick, currentMetric}: {
Done

2024-03-15 02:37 UTC, VolffS commented on src/components/week-info/week-info.tsx
> +                            onDayClick.selectWeatherDay(+ev.currentTarget.id);
Done

2024-03-15 02:37 UTC, VolffS commented on src/components/week-info/week-info.tsx
> +    const dataWeek: Array<WeeksWeatherData> = formattingWeeksWeatherData(weatherInfo);
Done

2024-03-15 02:37 UTC, VolffS commented on src/components/main-content/main-content.tsx
> +                    <CurrentWeather weather={stateWeather} weatherDay={weatherDay} currentMetric={weatherMetric}/>
Done

2024-03-15 02:37 UTC, VolffS commented on src/components/main-content/main-content.tsx
> +                    weather.main.temp = weather.main.temp * 1.8 + 32
Done

2024-03-15 02:38 UTC, VolffS commented on src/components/main-content/main-content.tsx
> +        if (weatherDay === day) {
Done

2024-03-15 02:38 UTC, VolffS commented on src/components/main-content/main-content.tsx
> +    const [weatherMetric, setWeatherMetric] = useState<Metric>(Metric.celsius);
Done

2024-03-15 02:38 UTC, VolffS commented on src/components/main-content/main-content.tsx
> +        navigator.geolocation.getCurrentPosition(successGetCurrentPosition);
Like

2024-03-15 02:38 UTC, VolffS commented on src/components/main-content/main-content.tsx
> +    const [stateWeather, setStateWeather] = useState<WeatherData>({
Done

2024-03-15 02:38 UTC, VolffS commented on src/components/main-content/main-content.tsx
> +                        const date = new Date(day.dt_txt).getHours();
Done

2024-03-15 02:38 UTC, VolffS commented on src/components/main-content/main-content.tsx
> +    const downEscapeHandler = (ev: KeyboardEvent): void => {
Done

2024-03-15 02:39 UTC, VolffS commented on src/components/main-content/main-content.tsx
> +        window.addEventListener("keydown", downEscapeHandler)
Done

2024-03-15 02:39 UTC, VolffS commented on src/components/search-result-list/search-result-list.tsx
> +export const SearchResultList = ({cities, onDivClick}: {
Done

2024-03-15 02:39 UTC, VolffS commented on src/components/search-result-list/search-result-list.tsx
> +        <ul className="country-search__result">
Done

2024-03-15 02:40 UTC, VolffS commented on src/components/side-information/side-information.tsx
> +export const SideInformation = ({weather, onBtnClick, useWeatherDay, currentMetric}: {
Done

2024-03-15 02:40 UTC, VolffS commented on src/components/side-information/side-information.tsx
> +        <WeekInfo weatherInfo={weather} onDayClick={useWeatherDay} currentMetric={currentMetric}/>
Может, а может в другом месте. Done

2024-03-15 02:40 UTC, VolffS commented on src/components/current-weather/current-weather.tsx
> +    const weatherData: TodayWeather = formattingWeatherByDate(weather, weatherDay, currentMetric);
Done

2024-03-15 02:40 UTC, VolffS commented on src/type/geolocation.ts
> +        accuracy: number,
Done

2024-03-15 02:40 UTC, VolffS commented on src/helpers/helpers.ts
> +export function throttle(func, ms) {
Done

2024-03-15 07:27 UTC, xDSUP approved these changes

2024-03-15 07:27 UTC, xDSUP commented on src/components/main-content/main-content.tsx
> +	const WeatherForecast: UseWeather = useWeather();
переменная с большой буквы

2024-03-15 07:27 UTC, xDSUP commented on src/components/main-content/main-content.tsx
> +				className="loader-background disabled-loader"
className={`loader-background disabled-loader ${WeatherForecast.isLoad && 'disabled-loader'}`}

2024-03-15 07:28 UTC, xDSUP commented on src/components/main-content/main-content.tsx
> +				className="loader-background disabled-loader"
className={`loader-background disabled-loader ${WeatherForecast.isLoad && 'disabled-loader'}`}

2024-03-15 07:29 UTC, xDSUP commented on src/components/main-content/main-content.tsx
> +	if (loaderRef.current !== undefined && !WeatherForecast.isLoad) {
Ну низя так, В ногу выстрелят такие манипуляции с класслистом неявные. убираем)

2024-03-15 07:38 UTC, xDSUP commented on src/components/main-content/main-content.tsx
> +			.finally(() => loaderRef.current.classList.remove('disabled-loader'));
лишнее, внутри refreshStateWeather уже isLoad меняется, и там правильное место, где это логика и должна быть. А вот это навешивание класса исходя из стейта должно быть по место, где лоадер обьявляется

2024-03-15 07:55 UTC, xDSUP commented on src/type/use-weather.ts
> +export interface UseWeather {
use только для названия хуков, эту штуку можно назвать weatherState

2024-03-15 07:55 UTC, xDSUP commented on src/type/use-weather.ts
> +	stateWeather: WeatherData;
а это уж data)

2024-03-15 09:02 UTC, xDSUP commented on src/components/country-search/country-search.tsx
> +						onCityClick={cancelCountrySearch}
ну почему отмена то?) это же выбор города какой-нибудь)

2024-03-15 09:36 UTC, xDSUP commented on src/components/country-search/country-search.tsx
> +export const CountrySearch = ({
чет не работает поиск(

2024-03-15 09:54 UTC, xDSUP commented on src/helpers/helpers.ts
> +export enum Metric {
TemperatureMetric

2024-03-15 10:09 UTC, xDSUP commented on src/components/current-weather/current-weather.tsx
> +	const weatherData: TodayWeather = formattingWeatherByDate(weather, weatherMetric);
Тут получается фигнюшка, ты хранишь данные в формате ответа апишки, а потом их преобразовываешь в компонентах. Предлагаю эти форматирования сразу вынести в хук общения c API

2024-03-15 10:10 UTC, xDSUP commented on src/hooks/useWeather.ts
> +				day.main.temp = formattingFahrenheit(day.main.temp);
насколько тебе будет больно, если попросят добавить в кальвинах?)

2024-03-15 10:12 UTC, xDSUP commented on src/components/week-info/week-info.tsx
> +								{value.temp}
formatingTemperature(tempInCells: num, metric: TemperatureMetric(твой Metric))  вот тут вот и нужно пересчитывать

2024-03-15 10:13 UTC, xDSUP commented on src/components/today-extra-weather/today-extra-weather.tsx
> +					{Math.floor(currentWeather.main.feels_like)}
и вот тут formatingTemperature(tempInCells: num, metric: TemperatureMetric(твой Metric))

2024-03-15 10:14 UTC, xDSUP commented on src/components/current-weather/current-weather.tsx
> +					<p className="current-weather__down__temp">{weatherData.temperature}</p>
formatingTemperature(tempInCells: num, metric: TemperatureMetric(твой Metric)) и тут пересчет в нужную метрику

2024-03-15 10:16 UTC, xDSUP commented on src/helpers/helpers.ts
> +export const formattingWeatherByDate = (
Такая штука называется не formatting, а map(маппинг из одной структуры в другую)

2024-03-15 10:18 UTC, xDSUP commented on src/components/main-content/main-content.tsx
> +						<CurrentWeather weather={WeatherForecast.getForecastForDay(activeDay)} />
activeDay загони в   WeatherForecast внутрь хука, пусть там отслеживается.

2024-03-15 10:31 UTC, xDSUP requested changes

2024-03-15 10:31 UTC, xDSUP commented on src/hooks/useWeather.ts
> +				setStateWeather(weatherData);
вот тут вот можно вызвать твои мапинги типа formattingWeeksWeatherData и хранить уже их результат

2024-03-15 12:40 UTC, VolffS commented on src/helpers/helpers.ts
> +export const formattingWeatherByDate = (
У обычных людей это формат называется

2024-03-15 16:29 UTC, VolffS commented on src/hooks/useWeather.ts
> +				day.main.temp = formattingFahrenheit(day.main.temp);
done

2024-03-15 16:29 UTC, VolffS commented on src/components/current-weather/current-weather.tsx
> +	const weatherData: TodayWeather = formattingWeatherByDate(weather, weatherMetric);
done

2024-03-15 16:29 UTC, VolffS commented on src/helpers/helpers.ts
> +export enum Metric {
done

2024-03-15 16:29 UTC, VolffS commented on src/components/country-search/country-search.tsx
> +export const CountrySearch = ({
done

2024-03-15 16:30 UTC, VolffS commented on src/components/country-search/country-search.tsx
> +						onCityClick={cancelCountrySearch}
done

2024-03-15 16:32 UTC, VolffS commented on src/type/use-weather.ts
> +	stateWeather: WeatherData;
done

2024-03-15 16:32 UTC, VolffS commented on src/type/use-weather.ts
> +export interface UseWeather {
data

2024-03-15 16:34 UTC, VolffS commented on src/hooks/useWeather.ts
> +				setStateWeather(weatherData);
done

2024-04-05 18:38 UTC, merged